### PR TITLE
Fixes relating rofi font issues.

### PR DESCRIPTION
**Pull request by Maximumtix**

### CODE REVIEW

**Comment by owl4ce** [comment]
The `feather 17` font is not quite right. `feather 18` will fill all sides.

**Comment by Maximumtix** [comment]
I cannot increase the font size to 18 because, It breaks all sidebars.

**Review by owl4ce — APPROVED** [review]
Adjusted the layout with a font size of 17px.

**Comment by owl4ce** [comment]
**@Maximumtix** 
Is this layout appropriate? It will be merged if everything is correct.

**Comment by Maximumtix** [comment]
Difference between `  menu-element-padding:                 22px 23px 18px 3px;` and ` menu-element-padding:                 21px 23px 19px 3px;` 
21px : 

22px :

 menu-element-padding:                 22px 23px 20px 3px;(as well as 4px version) produces a blank menu
4 px is making a "next page" like menu for me 
4px

**Comment by owl4ce** [comment]
> Difference between ` menu-element-padding: 22px 23px 18px 3px;` and ` menu-element-padding: 21px 23px 19px 3px;`
> 21px :
> 
> 22px :
> 
> menu-element-padding: 22px 23px 20px 3px;(as well as 4px version) produces a blank menu
> 4 px is making a "next page" like menu for me
> 4px

Only occurs in configurations using 4px?

**Comment by Maximumtix** [comment]
`menu-element-padding: 21px 23px 19px 3px;` and `menu-element-padding: 22px 23px 18px 3px;` is indistinguishable for me. So choose the best looking for you.

**Comment by owl4ce** [comment]
> `menu-element-padding: 21px 23px 19px 3px;` and `menu-element-padding: 22px 23px 18px 3px;` is indistinguishable for me. So choose the best looking for you.
> Oh and maybe test it on a 1080p display

Yeah, we need more tester 😄

**Comment by owl4ce** [comment]
Ok, I'll change to as soon as possible.
`menu-element-padding: 21px 23px 19px 3px;`

**Comment by Maximumtix** [comment]
I tested the changes on my 1080p TV. I got the same results. Are you going to merge your or my commits?

**Review by owl4ce — APPROVED** [review]
Are we ready to merge this PR? @Maximumtix

**Comment by Maximumtix** [comment]
> `menu-element-padding: 21px 0px 18px 3px` is not working
> vertical
> and once again i measured the menu with a ruler and 2px perfectly symmetrical but 3px is 1mm off to the right.

**Comment by Maximumtix** [comment]
Vertical sidebars should be `menu-element-padding: 20px 0px 17px 3px`

**Comment by Maximumtix** [comment]
Or do you have any suggestions? How does my example commit look on your display?

**Comment by owl4ce** [comment]
> Vertical sidebars should be `menu-element-padding: 20px 0px 17px 3px`

How about `menu-element-padding: 20px 0px 18px 3px` ?

**Comment by owl4ce** [comment]
> Or do you have any suggestions? How does my example commit look on your display?

Yes, that's fine but the padding is too wide at the bottom.

**Comment by Maximumtix** [comment]
> > Vertical sidebars should be `menu-element-padding: 20px 0px 17px 3px`
> 
> How about `menu-element-padding: 20px 0px 18px 3px` ?

Doesn't work :(

**Comment by owl4ce** [comment]
> > > Vertical sidebars should be `menu-element-padding: 20px 0px 17px 3px`
> > 
> > 
> > How about `menu-element-padding: 20px 0px 18px 3px` ?
> 
> Doesn't work :(

Like https://github.com/owl4ce/dotfiles/pull/80#issuecomment-819368371 ?

**Comment by Maximumtix** [comment]
> > `menu-element-padding: 21px 0px 18px 3px` is not working
> > vertical
> > and once again i measured the menu with a ruler and 2px perfectly symmetrical but 3px is 1mm off to the right.

yep looks like this

**Comment by owl4ce** [comment]
> > > `menu-element-padding: 21px 0px 18px 3px` is not working
> > > vertical
> > > and once again i measured the menu with a ruler and 2px perfectly symmetrical but 3px is 1mm off to the right.
> 
> yep looks like this

Ok, approved changes to 17px.

**Comment by Maximumtix** [comment]
May I see how does 20 0 17 3 looks on your display?

**Comment by owl4ce** [comment]
> May I see how does 20 0 17 3 looks on your display?

Sure
2021-04-15-025108_1366x768_scrot

**Comment by Maximumtix** [comment]
Can you try 18 0 19 3?

**Comment by owl4ce** [comment]
> Can you try 18 0 19 3 and 19 0 18 3

I think, 20 0 17 3 still better centered glyphs

`menu-element-padding:                 18px 0px 19px 3px;`
2021-04-15-030044_1366x768_scrot

`menu-element-padding:                 19px 0px 18px 3px;`
2021-04-15-030236_1366x768_scrot

**Comment by owl4ce** [comment]
Oh maybe 19 0 18 3 better

**Comment by Maximumtix** [comment]
> Oh maybe 19 0 18 3 better. Yeah, thats it.

Are you sure? Isn't bottom too spacious? I am spamming numbers in my config but I can't make it work

**Comment by owl4ce** [comment]
> > Oh maybe 19 0 18 3 better. Yeah, thats it.
> 
> Are you sure? Isn't bottom too spacious? I am spamming numbers in my config but I can't make it work

Actually I still want to go to `menu-element-padding:                 21px 0px 18px 3px;`

Can you change the height? Make it higher.
https://github.com/owl4ce/dotfiles/blob/37b99d44b9d87cd5837267b74aba645f596b5be5/.config/rofi/themes/sidebar/five-vertical.rasi#L13-L21

**Comment by owl4ce** [comment]
I want to see, what heights that match with `menu-element-padding:                 21px 0px 18px 3px;` in your device.

**Comment by Maximumtix** [comment]
It worked!!!   `menu-element-padding:             21px 0px 18px 3px;`    and height is 365px

**Comment by owl4ce** [comment]
> It worked!!! `menu-element-padding: 21px 0px 18px 3px;` and height is 365px

Mine 😄 

2021-04-15-031803_1366x768_scrot

**Comment by owl4ce** [comment]
I'm still wondering why ... by the way my dpi is 96

**Comment by Maximumtix** [comment]
> > It worked!!! `menu-element-padding: 21px 0px 18px 3px;` and height is 365px
> 
> Mine smile
> 
> 2021-04-15-031803_1366x768_scrot

oh.... maybe we should play with y-offset?

**Comment by owl4ce** [comment]
> > > It worked!!! `menu-element-padding: 21px 0px 18px 3px;` and height is 365px
> > 
> > 
> > Mine smile
> > 2021-04-15-031803_1366x768_scrot
> 
> oh.... maybe we should play with y-offset?

no, its location in screen. not size.

**Comment by owl4ce** [comment]
Fine, I'll try to experiment with that again later.

**Comment by Maximumtix** [comment]
15.6inches 1366x768 = 100dpi

**Comment by owl4ce** [comment]
> 15.6inches 1366x768 = 100dpi

Oww, maybe screen inchs, I'm trying to change dpi to `100` but nothing happened.

**Comment by Maximumtix** [comment]
Another configıration to try may be 20px 0px 18px 3px with 360px height

**Comment by owl4ce** [comment]
> Another configıration to try may be 20px 0px 18px 3px with 360px height

It's the same in fact, it's just like shifting glyphs.

**Comment by owl4ce** [comment]
@Maximumtix 
The best options is sticking to 17px.

**Comment by Maximumtix** [comment]
21 0 17 3 works with 360px height

**Comment by owl4ce** [comment]
> 21 0 17 3 works with 360px height (five-vertical)

Bruh, actually same with https://github.com/owl4ce/dotfiles/pull/80#issuecomment-819817032

😢

**Comment by owl4ce** [comment]
Until now, I'm still confused about what to do. Didn't find a solution to the above problems. 😢

**Comment by owl4ce** [comment]
Obsolete. JDv4 has [different configuration](https://github.com/owl4ce/dotfiles/tree/4.0_WIP/.config/rofi) with better UI (custom-modi).

**Pull request closed without merging**
