### PR TITLE
Major Fixes (clean up syntax, etc.)

### PR DESCRIPTION
**Pull request by owl4ce**

### CODE REVIEW

**Review by owl4ce — COMMENTED** [review]
Done.

**Comment by akinokonomi** [comment]
Sorry for meddling in, but what is the meaning of this change?
```diff
- export LC_ALL=C LANG=C; . "${HOME}/.owl4ce_var"
+ export LC_ALL=POSIX; . "${HOME}/.owl4ce_var"
```
Namely, this:
```diff
- export LC_ALL=C LANG=C;
+ export LC_ALL=POSIX;
```
?

**Comment by owl4ce** [comment]
> Sorry for meddling in, but what is the meaning of this change?
> 
> ```diff
> - export LC_ALL=C LANG=C; . "${HOME}/.owl4ce_var"
> + export LC_ALL=POSIX; . "${HOME}/.owl4ce_var"
> ```
> 
> Namely, this:
> 
> ```diff
> - export LC_ALL=C LANG=C;
> + export LC_ALL=POSIX;
> ```
> 
> ?

Actually does nothing, basically C and POSIX locale is the same, but I prefer use POSIX. Why overriding locale for some shell script? It's a bit speeding up script execution by disabling UTF-8.

**Comment by akinokonomi** [comment]
> Actually does nothing, basically C and POSIX locale is the same, but I prefer use POSIX.

Right.

> It's a bit speeding up script execution by disabling UTF-8.

Oh, is it? I thought you just have a different variable already set.

I have none, myself:
```sh
 $ locale | grep LC_ALL
LC_ALL=
```
If I don't `export LC_ALL=C|POSIX;`, would it fallback to my `LANG` then?

**Comment by akinokonomi** [comment]
> It's a bit speeding up script execution by disabling UTF-8.

But you still have `#!/usr/bin/env *bash*` not `*sh*`; does `LC_ALL=POSIX;` really help?

**Comment by owl4ce** [comment]
Sorry for the late reply due to busy.

---

> If I don't export LC_ALL=C|POSIX;, would it fallback to my LANG then?

Yes, but I just figuring out that `LC_ALL` **implies** `LC_*` excluding `LANG`. I forgot about that, I'll fix it ASAP. Check it.

```sh
LC_ALL=POSIX locale
```

> But you still have #!/usr/bin/env *bash* not *sh*; does LC_ALL=POSIX; really help?

Locale doesn't affects the shell functions, but the unicodes. IMHO.

**Comment by owl4ce** [comment]
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap07.html

https://unix.stackexchange.com/questions/571842/what-does-in-the-posix-locale-mean

**Comment by akinokonomi** [comment]
> `LC_ALL` **implies** `LC_*` excluding `LANG`

I see.

> Locale doesn't affects shell functions, but unicodes.

Yes, so even by simply excluding `UTF-8` there will be a speed up, then?

EDIT: Why do not you use shell instead of bash?

**Comment by owl4ce** [comment]
> Yes, so even by simply excluding UTF-8 there will be a speed up, then?

Basically useful for complex script, since the env var exported until child-processes. No problem to use it :), except for program that needs UTF-8 like curses-based programs.

> Why do not you use shell instead of bash?

Good question! Some scripts in this dotfiles still rely on bash e.g REGEX in `[[ ]]`, array `VAR=()` on ncmpcpp scripts, etc. I'll try to rewrote all scripts on the next update to POSIX-sh (tested under dash) if possible.

**Comment by akinokonomi** [comment]
> Some scripts in this dotfiles still rely on bash e.g REGEX in `[[ ]]`, array `VAR=()` on ncmpcpp scripts, etc.

But there is no problem in having them in both bash and shell, for bash scripts you could use `.bash` extension to easily discern them.

**Comment by owl4ce** [comment]
and this one is good

https://github.com/owl4ce/dotfiles/blob/2d3f45d80b27ad146dc58de8595653226a08c5e5/.owl4ce_var#L220-L225

**Comment by owl4ce** [comment]
Thank you @akinokonomi for your suggestion. I appreciate it!

**Comment by akinokonomi** [comment]
> and this one is good [...]

Sorry, I don't understand.

You mean POSIX-, Shell-compliant?

**Comment by akinokonomi** [comment]
> Thank you @akinokonomi for your suggestion.

I thank you too. I learned just too many things to count from reviewing your repository.

**Comment by owl4ce** [comment]
> > and this one is good [...]
> 
> Sorry, I don't understand.
> 
> You mean POSIX-, Shell-compliant?

Did you mean POSIX-sh? Yes, it's POSIX-compliant shell. I usually use `dash` to test it.

**Comment by akinokonomi** [comment]
> Did you mean POSIX-sh? 

Yes, that is what I meant. But what did you try to say by "and this one is good"?

**Comment by owl4ce** [comment]
> But what did you try to say by "and this one is good"?

It's bashism :)

It faster (than `cat`) to read files using direct stdin.

**Comment by akinokonomi** [comment]
Oh, so `<file` is not shell-compliant?

EDIT: Yes, it is not.

**Pull request merged**
