### PR TITLE
some: added

### PR DESCRIPTION
**Pull request by vcyzteen**
added urxvt: copy paste with ctrl + shift + c for copy and ctrl + shift + v ( for paste )
test: round openbox-pacthed
GIMP: change splash default to okita souji

thanks this is very beautifull dotfiles and i hope this can added :")

### CODE REVIEW

**Comment by owl4ce** [comment]
**Hi @vcyzteen** 
Openboxnya ini udah rounded kak

**Comment by owl4ce** [comment]
The problem here is don't add a new line, it will break all bash scripts.

**Comment by vcyzteen** [comment]
> **Hi @vcyzteen**
> Openboxnya ini udah rounded kak, dari picom bukannya rounded semua?
> 
> _The Openbox is already rounded from picom, isn't it all rounded?_

iya kak kalo pake picom ini sudah bulat tapi picom berat di laptop ram 4 dengan grafik kartu intel seri u kebawah jadi mungkin ini bisa membantu jika ada orang yang mennggunakan openbox-pacthed karena openbox-pacthed lebih ringan dri pada picom hehehe. terimakasih atas responnya kak :")

**Comment by vcyzteen** [comment]
> The problem here is don't add a new line, it will break all bash scripts that related to `sed`.
> I will try to outsmart, or do something first.
> 
> I received copy and paste, it means that this deletes the `clipboard` extension that was originally there to urxvt `default` extension.

ok sir thanks for the reply if you can't maybe I'll add the manual hehehe: ")

**Comment by owl4ce** [comment]
**Bruh,** really sure picom is laggy? Here I'm using 4GiB RAM, AMD HD 512MiB VRAM. Don't feel any lag at all 😄 


Product Name | HP 14 G102AU
-- | --
Product Number | K8U80PA
Microprocessor | 1.5 GHz AMD Quad-Core A4-5000 APU with Radeon HD 8330 Graphics
Chipset | Intel HM87 Express
Microprocessor Cache | 2 MB cache
Memory | 4 GB 1600 MHz DDR3L SDRAM (1 x 4 GB)
Memory Slots | 1 user-accessible
Video Graphics | AMD Radeon HD 8330 Graphics
Display | 14" diagonal HD BrightView WLED-backlit (1366 x 768)
Hard Drive | 500 GB Toshiba 5400 rpm SATA
Solid State Drive | 120 GB Adata SU650 Sequential R/W 520 / 450MB/s SATA
Network Card | Integrated 10/100 BASE-T Ethernet LAN
Wireless Connectivity | 802.11b/g/n (1x1) and Bluetooth 4.0 - Qualcomm Atheros AR9485
Sound | Dual speakers
Keyboard | Full-size textured island-style
Pointing Device | Touchpad with multi-touch gesture support
External Ports | 1 multi-format SD media card reader 1 USB 3.0 2 USB 2.0 1 HDMI 1 VGA 1 RJ-45 1 headphone/microphone combo
Dimensions | 34.5 x 24.4 x 2.53 cm
Weight | Starting at 1.96 kg
Power | 45 W AC power adapter 4-cell, 41 Wh Li-ion
Camera | HP TrueVision HD Webcam (front-facing) with integrated digital microphone

**Comment by vcyzteen** [comment]
> **Bruh,** really sure picom is laggy? Here I'm using 4GiB RAM, AMD HD 512MiB VRAM. Don't feel any lag at all 
> 
> Product Name	HP 14 G102AU
> Product Number	K8U80PA
> Microprocessor	1.5 GHz AMD Quad-Core A4-5000 APU with Radeon HD 8330 Graphics
> Chipset	Intel HM87 Express
> Microprocessor Cache	2 MB cache
> Memory	4 GB 1600 MHz DDR3L SDRAM (1 x 4 GB)
> Memory Slots	1 user-accessible
> Video Graphics	AMD Radeon HD 8330 Graphics
> Display	14" diagonal HD BrightView WLED-backlit (1366 x 768)
> Hard Drive	500 GB Toshiba 5400 rpm SATA
> Solid State Drive	120 GB Adata SU650 Sequential R/W 520 / 450MB/s SATA
> Network Card	Integrated 10/100 BASE-T Ethernet LAN
> Wireless Connectivity	802.11b/g/n (1x1) and Bluetooth 4.0 - Qualcomm Atheros AR9485
> Sound	Dual speakers
> Keyboard	Full-size textured island-style
> Pointing Device	Touchpad with multi-touch gesture support
> External Ports	1 multi-format SD media card reader 1 USB 3.0 2 USB 2.0 1 HDMI 1 VGA 1 RJ-45 1 headphone/microphone combo
> Dimensions	34.5 x 24.4 x 2.53 cm
> Weight	Starting at 1.96 kg
> Power	45 W AC power adapter 4-cell, 41 Wh Li-ion
> Camera	HP TrueVision HD Webcam (front-facing) with integrated digital microphone

hmmm i don't know sir im use laptop idealpad lenovo g30-40 normally speck this ram 2 and hdd 500gb soc Intel® Celeron® N2830 and now im upgrade my pc with ssd 225 and ram up to 4gb hehehe :")

**Comment by vcyzteen** [comment]
> > hmmm i don't know sir im use laptop idealpad lenovo g30-40 normally speck this ram 2 and hdd 500gb soc Intel® Celeron® N2830 and now im upgrade my pc with ssd 225 and ram up to 4gb and if im use picom feels iag a few second hehehe :")
> 
> Have you tried to disable blur in picom config?

yep i try but still feels lag i don't know why

**Comment by owl4ce** [comment]
**Why you close this PR?**
I'll do it for a moment. I accepted the GIMP splash idea, but not the file. Why? it doesn't match my concept, it doesn't edit at all.

**Comment by owl4ce** [comment]
Oh, sorry. Files cannot be edited.

**Comment by vcyzteen** [comment]
> Oh, sorry. Files cannot be edited.

what file sir?

**Pull request closed without merging**
